# Generated by Django 4.1.1 on 2022-11-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0004_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
