# Generated by Django 4.1.1 on 2022-11-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
