# Generated by Django 4.1.1 on 2022-11-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
