# Generated by Django 4.1.7 on 2023-05-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0024_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
