# Generated by Django 4.1.7 on 2023-05-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0025_product_rating_delete_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='products',
        ),
    ]
