# Generated by Django 4.1.7 on 2023-05-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0027_rename_products_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
