# Generated by Django 4.1.7 on 2023-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiqueapp', '0028_delete_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.ImageField(default='a3.png', upload_to='photos/display'),
        ),
        migrations.AddField(
            model_name='product',
            name='display2',
            field=models.ImageField(default='a3.png', upload_to='photos/display'),
        ),
        migrations.AddField(
            model_name='product',
            name='display3',
            field=models.ImageField(default='a3.png', upload_to='photos/display'),
        ),
    ]
